jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Gradle
      run: cd VirtualApp && ./gradlew assembleRelease
    - continue-on-error: true
      name: ls
      run: ls
    - continue-on-error: true
      name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: compiled
        path: VirtualApp/app/build/
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
